apiVersion: v1
kind: Service
metadata:
  labels:
    service: chameleon
    maintainer: data-reliability
  name: chameleon
  namespace: staging
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    service: chameleon
